services:
  db-usersvc:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  usersvc:
    image: golang:1.6.1-alpine
    build: .
    env_file:
      - ./config/app.env
    volumes:
      - .:/go/src/app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db-usersvc